# Generated by Django 4.1.3 on 2022-12-21 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("participantes", models.ManyToManyField(to="atas.participante")),
            ],
        ),
    ]
